#!/usr/bin/perl
# ------------------------------------------------------------------------------
# NAME
#   SCAR::RHEL6
#
# DESCRIPTION
#   Performs SCAR initialization tasks specific to Red Hat 6
#
# SEE ALSO
#   SCAR SCAR::RHEL
#
# AUTHOR
#   Erik Bowman (erik.bowman@icsinc.com)
#
# ------------------------------------------------------------------------------

package SCAR::RHEL6;

# Standard pragmas
use utf8;
use strict;
use warnings FATAL => 'all';

# Standard modules
use FindBin;

# SCAR modules
use SCAR;

# Module version
our $VERSION = 0.01;

# ------------------------------------------------------------------------------
# SYNOPSIS
#   new
#
# DESCRIPTION
#
# ARGUMENTS
#
# ------------------------------------------------------------------------------

sub new {
    my ( $class, $templates, $temp ) = @_;
    my $self = bless {
        templates => $templates,
        temp      => $temp,
    }, $class;

    return $self;
}

# ------------------------------------------------------------------------------
# SYNOPSIS
#   comment_string
#
# DESCRIPTION
#
# ------------------------------------------------------------------------------

sub comment_string {
    my ( $self, $vuln_id, $severity, $rule_id, $stig_id, $rule_title ) = @_;
    my $date_time    = SCAR->yyyymmdd . ' ' . SCAR->hhmmss;
    my $absolute_bin = File::Spec::Functions::catdir( $FindBin::Bin,
        $FindBin::RealScript );
    my $comment = <<"COMMENTTEXT";
# ------------------------------------------------------------------------------
# SECURITY COMPLIANCE AND REMEDIATION
#   This was automatically generated by $absolute_bin on $date_time
#
# VULN ID
#   $vuln_id
#
# SEVERITY
#   $severity
#
# RULE ID
#   $rule_id
#
# STIG ID
#   $stig_id
#
# RULE TITLE
#   $rule_title
# ------------------------------------------------------------------------------
COMMENTTEXT

    return $comment;
}

# ------------------------------------------------------------------------------

1;

__END__
