# ------------------------------------------------------------------------------
# NAME
#   Redhat::6::000145
#
# VULN ID
#   V-38628
#
# SEVERITY
#   medium
#
# GROUP TITLE
#   SRG-OS-000255
#
# RULE ID
#   SV-50429r2_rule
#
# STIG ID
#   RHEL-06-000145
#
# RULE TITLE
#   The operating system must produce audit records containing sufficient information to establish the identity of any user/subject associated with the event.
#
# TODO: Create Check
# TODO: Create Remediation
#
# AUTHOR
#   Erik Bowman (erik.bowman@icsinc.com)
#
# ------------------------------------------------------------------------------

package Redhat::6::000145;

# Standard modules
use utf8;
use strict;
use warnings FATAL => 'all';

# Scar modules
use Scar;
use Scar::Util::Log;
use Scar::Util::Backup;

# Plugin version
our $VERSION = 0.01;

sub new {
    my ( $class, $parent ) = @_;
    my $self = bless { parent => $parent }, $class;

    return $self;
}

sub check {
    my ($self) = @_;

    return $self;
}

sub remediate {
    my ($self) = @_;

    return $self;
}

sub _set_finding_status {
    my ( $self, $finding_status ) = @_;
    $self->{finding_status} = $finding_status;
    return $self->{finding_status};
}

sub get_finding_status {
    my ($self) = @_;
    return defined $self->{finding_status} ? $self->{finding_status} : undef;
}

sub get_vuln_id {
    return 'V-38628';
}

sub get_severity {
    return 'medium';
}

sub get_group_title {
    return 'SRG-OS-000255';
}

sub get_rule_id {
    return 'SV-50429r2_rule';
}

sub get_stig_id {
    return 'RHEL-06-000145';
}

sub get_rule_title {
    return
        'The operating system must produce audit records containing sufficient information to establish the identity of any user/subject associated with the event.';
}

sub get_discussion {
    return <<'DISCUSSION';
Ensuring the ""auditd"" service is active ensures audit records generated by the kernel can be written to disk, or that appropriate actions will be taken if other obstacles exist.
DISCUSSION
}

sub get_check_content {
    return <<'CHECK_CONTENT';
Run the following command to determine the current status of the ""auditd"" service:



# service auditd status



If the service is enabled, it should return the following:



auditd is running...





If the service is not running, this is a finding.
CHECK_CONTENT
}

sub get_fix_content {
    return <<'FIX_CONTENT';
The ""auditd"" service is an essential userspace component of the Linux Auditing System, as it is responsible for writing audit records to disk. The ""auditd"" service can be enabled with the following commands:



# chkconfig auditd on

# service auditd start
FIX_CONTENT
}

sub get_cci {
    return <<'CCI';
CCI-001487

The information system generates audit records containing information that establishes the identity of any individuals or subjects associated with the event.

NIST SP 800-53 :: AU-3

NIST SP 800-53A :: AU-3.1

NIST SP 800-53 Revision 4 :: AU-3




CCI
}

# ------------------------------------------------------------------------------

1;

__END__
